### ISSUE TITLE
Installing for Firefox

### ISSUE THREAD

**Issue by ghost** [marcelduran/yslow#1]
Hi,
Thanks so much for open sourcing yslow! I am trying to figure out how to install the firefox 'flavor' after cloning the repo. 

I run make firefox, and it generates the package (firefox directory is created with .rdf file). But inside firefox I choose to Install add on from file, and I cannot get it to install. 

Thanks for any help.
Dave

**Comment by marcelduran** [comment]
I suggest following Mozilla's article on building Firefox extensions. If you build rather than packaging you basically need to symlink the build directory from your FF profile extension directory: https://developer.mozilla.org/en/Building_an_Extension#Test

If you make the actual package, the .xpi file must be served as "application/x-xpinstall": https://developer.mozilla.org/en/Building_an_Extension#Package
